config/routes.rb
Rails.application.routes.draw do
  get 'genres/show'
  get 'customers/edit'
  get 'customers/show'
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords,], controllers: {
  registrations: "customer/registrations",
  sessions: 'customer/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

#Customer側のルーティング
  root 'homes#top'
  get 'about' => 'homes#about'
  resources :items, only: [:index, :show]

  delete 'cart_items/all_destroy' => 'cart_items#all_destroy'
  resources :cart_items, only: [:index, :create, :update, :destroy]

  resource :customers, only: [:show, :edit, :update]
  patch 'customers/withdraw' => 'customers#withdraw'
  get 'customers/unsubscribe' => 'customers#unsubscribe'

  post 'orders/confirm' => 'orders#confirm'
  get 'orders/thanx' => 'orders#thanx'
  resources :orders, only: [:index, :show, :new, :create]


  resources :addresses, except: [:new, :show]


  #admin側のルーティング
  namespace :admin do
    resources :items, except: [:destroy]
    resources :genres, except: [:new, :show, :destroy]
    resources :customers, except: [:new, :create, :destroy]
    resources :orders, only: [:index, :show, :update]
    get 'customer_orders/:id', to: 'orders#index_customer', as: 'customer_orders'
    patch 'orders_details/:id', to: 'order_details#update'
  end

end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :customer
  has_many :order_items, dependent: :destroy

  enum payment_method: { credit_card:0, transfer:1 }
  enum status: { wating_for_deposit:0, payment_confirmation:1, be_making:2, ready_to_ship:3, has_been_shiped:4}

  def billing_amount
    shipping_cost + total_payment
  end
  
  validates :postcode, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :payment_method, presence: true

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index
    @orders = Order.page(params[:page]).per(10)
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @total = @order_items.inject(0) { |sum, cart_item| sum + cart_item.subtotal }
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    p @order
    if @order.status == "payment_confirmation"
      making_status = OrderItem.where(order_id: @order.id)
      making_status.update(making_status: "wating_for_making")
      redirect_to request.referer
    else
      redirect_to request.referer
    end
  end

  def index_customer
    @customer_orders = Order.where(customer_id: params[:id]).page(params[:page]).per(10)
    @customer_name = Order.find_by(customer_id: params[:id]).customer.full_name
  end


  private
    def order_params
      params.require(:order).permit(:status)
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
    @address = Address.all
    @customer = Customer.find(current_customer.id)
  end

  def create
    order = current_customer.orders.new(order_params)
    order.save
    cart_items = current_customer.cart_items
    cart_items.each do |cart_item|
    OrderItem.create(
      item_id: cart_item.item.id,
      order_id: order.id,
      quantity: cart_item.quantity,
      price: cart_item.subtotal
    )
    end
    cart_items.destroy_all
    redirect_to orders_thanx_path
  end


  def index
    @orders = current_customer.orders
  end

  def show
    @order = Order.find(params[:id])
    @order_items = OrderItem.where(order_id: params[:id])
    @total_payment = 0
    @order_items.each do |order_item|
      @total_payment += order_item.item.add_tax_sales_price * order_item.quantity
    end
    @amount_billed = @total_payment + @order.shipping_cost
  end

  def confirm
    @cart_items = current_customer.cart_items
    # <!--カートに入ってる商品の合計金額-->
    @total = @cart_items.inject(0) { |sum, cart_item| sum + cart_item.subtotal }
    @order = Order.new(order_params)
    @order.shipping_cost = 800.to_i
    if params[:order][:select_addres] == "0"
      @order.postcode = current_customer.postcode
      @order.address = current_customer.address
      @order.name = current_customer.last_name + current_customer.first_name
    elsif params[:order][:select_addres] == "1"
      @address = Address.find(params[:order][:address_id])
      @order.postcode = @address.postcode
      @order.address = @address.address
      @order.name = @address.name
    end
  end

  def thanx
  end

  private

  def order_params
    params.require(:order).permit(:payment_method, :postcode, :address, :name, :shipping_cost, :total_payment)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <h4 class = "bg-light my-3 px-4">注文履歴一覧</h4>
    <table class="table table-hover table-inverse mx-5">
      <thead class="thead-light">
       <tr>
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
       </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
        <tr>
          <td><u><%= link_to order.created_at.strftime("%Y/%m/%d %H:%M:%S"), admin_order_path(order.id), class: "text-dark" %></u></td>
          <td><u><%= link_to order.customer.full_name, admin_customer_orders_path(order.customer_id), class: "text-dark" %></u></td>
          <td><%= order.order_items.sum(:quantity) %></td>
          <td><%= order.status_i18n %></td>
        </tr>
       <% end %>
      </tbody>
    </table>
    <div class="mx-auto">
      <%= paginate @orders %>
    </div>
  </div>
</div>

app/views/admin/orders/index_customer.html.erb
<div class="container">
  <div class="row">
    <h4 class="bg-light my-3 px-4"><%= @customer_name %>さんの注文履歴一覧</h4>
    <table class="table table-hover table-inverse mx-5">
      <thead class="thead-light">
       <tr>
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
       </tr>
      </thead>
      <tbody>
        <% @customer_orders.each do |customer_order| %>
        <tr>
          <td><u><%= link_to customer_order.created_at.strftime("%Y/%m/%d %H:%M:%S"), admin_order_path(customer_order.id), class: "text-dark" %></u></td>
          <td><u><%= link_to customer_order.customer.full_name, admin_customer_path(customer_order.customer.id), class: "text-dark" %></u></td>
          <td><%= customer_order.order_items.sum(:quantity) %></td>
          <td><%= customer_order.status_i18n %></td>
        </tr>
       <% end %>
      </tbody>
    </table>
       <div class="mx-auto">
        <%= paginate @customer_orders %>
      </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col mt-3">
      <h4>注文履歴詳細</h4>
    	  <div class="row">
    	    <div class="col-md-8 mt-3">
    	      <table class="table table-borderless">
    	        <thead class="thead-light">
    	        <tr>
    	          <th>購入者</th>
    	          <td>
                 <u>
                   <%= link_to admin_customer_path(@order.customer.id), class: "text-dark" do %>
	                 <%= @order.customer.full_name %>
	                 <% end %>
	               </u>
	             </td>
            </tr>
            <tr>
	            <th>注文日</th>
	            <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
	          </tr>
	          <tr>
	            <th class="align-top">配送先</th>
	            <td>〒<%= @order.postcode %><br>
	                  <%= @order.address %><br>
                    <%= @order.name %>
              </td>
	          </tr>
	          <tr>
	            <th>支払方法</th>
	            <td><%= @order.payment_method_i18n %></td>
	          </tr>
	          <tr>
	            <th class="align-middle">注文ステータス</th>
	            <td>
	              <%= form_with(model: @order, url: admin_order_path(@order),method: :patch, local: true, class: "form-row") do |f| %>
                <%= f.select :status, Order.statuses_i18n.invert, {}, class:"custom-select my-1 mr-sm-2 col-6"  %>
                <%= f.submit "更新",class: "btn btn-success ml-3" %>
                <% end %>
              </td>
	          </tr>
	         </thead>
	      </table>
	    </div>
	  </div>
    <div class="row">
      <div class="col-md-8 mt-2">
        <table class="table table-bordered">
          <thead class="thead-light">
            <tr>
              <th>商品名</th>
              <th>単価(税込)</th>
              <th>数量</th>
              <th>小計</th>
              <th>制作ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @order_items.each do |order_item| %>
            <tr>
              <td><%= order_item.item.name %></td>
              <td><%= order_item.add_tax_sales_price.to_s(:delimited) %>円</td>
              <td><%= order_item.quantity %></td>
              <td><%= order_item.subtotal.to_s(:delimited) %>円</td>
              <td>
                <%= form_with url: admin_path(order_item), model:order_item, method: :patch, local:true do |s| %>
                  <%= s.select :making_status, OrderItem.making_statuses_i18n.invert, {prompt: 0}, {class: "custom-select my-1 mr-sm-2 col-7",required: true} %>
                  <%= s.submit "更新", class: "btn btn-success" %>
                <% end %>
              </td>
            <% end %>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="offset-md-1 d-flex align-items-center justify-content-bottom">
        <table class="table table-borderless">
          <tr>
            <th class="total table-color">商品合計</th>
            <td class="total text-right"><%= @total.to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <th class="total table-color">送料</th>
            <td class="total text-right"><%= @order.shipping_cost.to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <th class="total table-color">請求金額合計</th>
            <td class="total text-right"><%= @order.billing_amount.to_s(:delimited) %>円</td>
          </tr>
         </table>
   	</div>
  </div>
 </div>
</div>
</div>