config/routes.rb
Rails.application.routes.draw do
  get 'genres/show'
  get 'customers/edit'
  get 'customers/show'
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords,], controllers: {
  registrations: "customer/registrations",
  sessions: 'customer/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

#Customer側のルーティング
  root 'homes#top'
  get 'about' => 'homes#about'
  resources :items, only: [:index, :show]

  delete 'cart_items/all_destroy' => 'cart_items#all_destroy'
  resources :cart_items, only: [:index, :create, :update, :destroy]

  resource :customers, only: [:show, :edit, :update]
  patch 'customers/withdraw' => 'customers#withdraw'
  get 'customers/unsubscribe' => 'customers#unsubscribe'

  post 'orders/confirm' => 'orders#confirm'
  get 'orders/thanx' => 'orders#thanx'
  resources :orders, only: [:index, :show, :new, :create]


  resources :addresses, except: [:new, :show]


  #admin側のルーティング
  namespace :admin do
    resources :items, except: [:destroy]
    resources :genres, except: [:new, :show, :destroy]
    resources :customers, except: [:new, :create, :destroy]
    resources :orders, only: [:index, :show, :update]
    get 'customer_orders/:id', to: 'orders#index_customer', as: 'customer_orders'
    patch 'orders_details/:id', to: 'order_details#update'
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :items, through: :cart_items
  has_many :order_items

  validates :last_name,presence:true
  validates :first_name,presence:true
  validates :last_name_kana,presence:true
  validates :first_name_kana,presence:true
  validates :postcode,presence:true,length: { is: 7 }
  validates :phone_num,presence:true
  validates :address,presence:true

  #devise情報をパスワードなしで更新できるメソッド
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  # enumの設定
  enum is_deleted: { withdraw: true, active: false}

  # フルネーム（nilの場合を除く）
  def full_name
    self.last_name + self.first_name
  end

  # フルネーム（姓名の間にスペースあり）（nilの場合を除く）
  def show_full_name
    self.last_name + " " + self.first_name
  end

  # フルネームカナ（nilの場合を除く）
  def full_name_kana
    self.last_name_kana + " " + self.last_name_kana
  end

  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
    def index
      @customers = Customer.page(params[:page]).per(10)
    end
  
    def show
      @customer = Customer.find(params[:id])
    end
  
    def edit
      @customer = Customer.find(params[:id])
    end
  
    def update
      customer = Customer.find(params[:id])
      customer.update(customer_params)
      redirect_to admin_customer_path(customer.id)
    end
  
  
  
  private
    def customer_params
     params.require(:customer).permit(:id, :last_name, :first_name, :first_name_kana, :last_name_kana, :postcode, :address, :phone_num, :email, :is_deleted)
    end
    
end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def after_update_path_for(_resource)
    customers_path
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone_num, :email])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  #before_action :configure_sign_in_params, only: [:create]
  #before_action :customer_state, only: [:create]

  before_action :reject_customer, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  #会員の論理削除のための記述。退会後は、同じアカウントでは利用できない。
  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email])
    if @customer
      if @customer.valid_password?(params[:customer][:password]) && (@customer.is_deleted == "withdraw")
        flash[:notice] = "退会済みです。再度ご登録をしてご利用ください"
        redirect_to new_customer_registration_path
      else
        flash[:notice] = "項目を入力してください"
      end
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def edit
    @customer = Customer.find(current_customer.id)
  end

  def show
    @customer = Customer.find(current_customer.id)
  end

  def update
    @customer = Customer.find(current_customer.id)
    if @customer.update(customer_params)
      redirect_to customers_path(@customer.id)
    else
      render :show
    end
  end

  def withdraw #退会処理
    # = current_customerでも作動するはずもしくはshowと揃える。defult:falseないので実行未確認
    @customer = current_customer
    #is_deletedカラムをtrueに変更することで論理削除フラグを立てる
    @customer.update(is_deleted: true)
    #セッション情報を全て削除
    reset_session
    flash[:notice] = "退会処理を実行しました。またのご利用を心よりお待ちしております"
    #退会後にトップ画面に遷移
    redirect_to root_path
  end

  def unsubscribe #退会画面表示
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<div class="container">
  <div class="row">
    <h4 class="bg-light my-3 px-4"><%= @customer.full_name %>さんの会員情報編集</h4>
  </div>

    <%= form_with model:@customer, url:customers_path, local:true do |f| %>

      <div class="form-group row">
        <%= f.label :氏名,class: "col-12 col-md-3 col-lg-2 col-form-label" %>
        <div class="col-12 mb-3 mb-md-0 col-md-4 col-lg-3">
          <%= f.text_field :last_name, autofocus: true, class: "form-control", placeholder: "姓" %>
        </div>
        <div class="col-12 col-md-4 col-lg-3">
          <%= f.text_field :first_name, autofocus: true, class: "form-control", placeholder: "名" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :フリガナ,class: "col-12 col-md-3 col-lg-2 col-form-label" %>
        <div class="col-12 col-md-4 mb-3 mb-md-0 col-lg-3 ">
          <%= f.text_field :last_name_kana, autofocus: true, class: "form-control", placeholder: "セイ" %>
        </div>
        <div class="col-12 col-md-4 col-lg-3">
          <%= f.text_field :first_name_kana, autofocus: true, class: "form-control mr-2", placeholder: "メイ" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :郵便番号, class: "col-12 col-md-3 col-lg-2 col-form-label" %>
        <div class="col-12 col-md-4 col-lg-3">
          <%= f.text_field :postcode, autofocus: true, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :住所,class: "col-12 col-md-3 col-lg-2 col-form-label" %>
        <div class="col-12 col-md-6">
          <%= f.text_field :address, autofocus: true, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :電話番号,class: "col-12 col-md-3 col-lg-2 col-form-label" %>
        <div class="col-12 col-md-4 col-lg-3">
          <%= f.text_field :phone_num, autofocus: true, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :メールアドレス,class: "col-12 col-md-3 col-lg-2 col-form-label" %>
        <div class="col-12 col-md-4 col-lg-3">
          <%= f.text_field :email, autofocus: true, class: "form-control" %>
        </div>
      </div>

      <div class="row">
        <p class="bg-light my-3 px-4"><%= f.submit "編集内容を保存", class: "btn btn-success" %></td>
        <p class="bg-light my-3 px-4"><%= link_to '退会する',customers_unsubscribe_path(@customer), class: "btn btn-danger" %></td>
      </div>
    <% end %>
  </div>

app/views/customers/show.html.erb
<div class="container">
  <div class="row">
    <h4 class="bg-light my-3 px-4"><%= @customer.full_name %>さんのマイページ</h4>
  </div>
  <br>
  <div class="row">
    <h3>　登録情報</h3>
    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
    <%= link_to "編集する", customers_edit_path(current_customer),class: "btn btn-success" %></p>
  </div>

    <br>
    <table border="1" width="600" height="300">
      <tr>
        <td width="200" bgcolor="silver">氏名</td>
        <td width="400"><%= @customer.last_name %><%= @customer.first_name %></td>
      </tr>
      <tr>
        <td width="200" bgcolor="silver">カナ</td>
        <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
      </tr>
      <tr>
        <td width="200" bgcolor="silver">郵便番号</td>
        <td><%= @customer.postcode %></td>
      </tr>
      <tr>
        <td width="200" bgcolor="silver">住所</td>
        <td><%= @customer.address %></td>
      </tr>
      <tr>
        <td width="200" bgcolor="silver">電話番号</td>
        <td><%= @customer.phone_num %></td>
      </tr>
      <tr>
        <td width="200" bgcolor="silver">メールアドレス</td>
        <td><%= @customer.email %></td>
      </tr>
    </table>

    <br>
    <table width="200" height="100">
      <tr>
        <th>配送先</th>
        <th><%= link_to '一覧を見る', addresses_path, class: "btn btn-primary" %></th>
      </tr>
      <tr>
        <th>注文履歴</th>
        <th><%= link_to '一覧を見る', orders_path,class: "btn btn-primary" %></th>
      </tr>
    </table>
</div>

app/views/customers/unsubscribe.html.erb
<div class="container">
  </br>
  </br>
  </br>
  </br>
  </br>
  </br>
  <h3 class="display-6 text-center font-weight-bold mb-4 ">本当に退会しますか？</h3>
　<p class="text-center lead">退会すると、会員登録情報や</br>
　これまでの購入履歴が閲覧できなくなります。</br>
  退会する場合は、「退会する」をクリックしてください。</br>

  <div class="row">
    <div class="col text-center">
      <%= link_to '退会しない',customers_path(@customer),class: "btn btn-primary" %>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <%= link_to '退会する',customers_withdraw_path,method: :patch, data: {confilm: "本当に退会しますか？" }, class: "btn btn-danger" %>
    </div>
  </div>
</div>