config/routes.rb
Rails.application.routes.draw do
  get 'genres/show'
  get 'customers/edit'
  get 'customers/show'
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords,], controllers: {
  registrations: "customer/registrations",
  sessions: 'customer/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

#Customer側のルーティング
  root 'homes#top'
  get 'about' => 'homes#about'
  resources :items, only: [:index, :show]

  delete 'cart_items/all_destroy' => 'cart_items#all_destroy'
  resources :cart_items, only: [:index, :create, :update, :destroy]

  resource :customers, only: [:show, :edit, :update]
  patch 'customers/withdraw' => 'customers#withdraw'
  get 'customers/unsubscribe' => 'customers#unsubscribe'

  post 'orders/confirm' => 'orders#confirm'
  get 'orders/thanx' => 'orders#thanx'
  resources :orders, only: [:index, :show, :new, :create]


  resources :addresses, except: [:new, :show]


  #admin側のルーティング
  namespace :admin do
    resources :items, except: [:destroy]
    resources :genres, except: [:new, :show, :destroy]
    resources :customers, except: [:new, :create, :destroy]
    resources :orders, only: [:index, :show, :update]
    get 'customer_orders/:id', to: 'orders#index_customer', as: 'customer_orders'
    patch 'orders_details/:id', to: 'order_details#update'
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord



  belongs_to :customer
  belongs_to :item


  def subtotal
    item.add_tax_sales_price * quantity
  end


end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_customer!

  def index
    @cart_items = current_customer.cart_items

    # <!--カートに入ってる商品の合計金額-->
    @total = @cart_items.inject(0) { |sum, cart_item| sum + cart_item.subtotal }

  end

  def show
    @cart_items = current_customer.cart_items
  end

  def create
    @cart_item = current_customer.cart_items.new(cart_item_params)
    #カートの中に同じ商品が重複しないようにして古い商品と新しい商品の数量を合計する。
    @update_cart_item = CartItem.find_by(item: @cart_item.item)
    if @update_cart_item.present? && @cart_item.valid?
      @cart_item.quantity += @update_cart_item.quantity
      @update_cart_item.destroy
    end
    if @cart_item.save
      flash[:notice] = "#{@cart_item.item.name}をカートに追加しました"
      redirect_to items_path
    end
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(quantity: params[:quantity].to_i)
    flash[:success] = "#{@cart_item.item.name}の数量を変更しました"
    redirect_to request.referer
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_items_path(@cart_item)
  end

  def all_destroy
    @cart_items = current_customer.cart_items
    @cart_items.destroy_all
    redirect_to cart_items_path(@cart_item)
  end

  private

  def cart_item_params
    params.permit(:item_id, :quantity)
  end

end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<div class="container">
  <div class="row">
    <h4 class = "bg-light my-4 px-4">ショッピングカート</h4>
    <% if @cart_items.count != 0 %>
    <div class = "bg-light my-4 px-4">
      <%= link_to "カートを空にする",cart_items_all_destroy_path(@cart_items.all), method: :delete, class: "btn btn-danger btn-sm" %>
    </div>
    </div>

    <table class='table table-hover table-inverse mx-5'>
      <thead>
        <tr bgcolor="#c0c0c0">
          <th>商品名</th>
          <th>単価(税込)</th>
          <th>数量</th>
          <th>小計</th>
          <th colspan="2"></th>
        </tr>
      </thead>
      <% @cart_items.each do |cart_item| %>
      <tbody>
        <tr>
          <td><%= attachment_image_tag cart_item.item, :image, :fill, 50, 50, format:"jpeg" %> <%= cart_item.item.name %></td>
          <td><%= cart_item.item.add_tax_sales_price.to_s (:delimited) %>　円</td>
          <td>
            <%= form_with model:@cart_item, url: cart_item_path(cart_item), method: :patch, local: true do |f| %>
              <%= f.select :quantity,options_for_select((1..10),{selected: cart_item.quantity.to_i}), class: "quantity" %>
              <%= f.submit "変更",class: "btn btn-info" %>
            <% end %>
          </td>
          <td><%= cart_item.subtotal.to_s (:delimited) %>　円</td>
          <td><%= link_to "削除する",cart_item_path(cart_item.id), method: :delete, local: true, class: "btn btn-danger btn-sm" %></td>
        </tr>
      </tbody>
      <% end %>
      </table>
      <br/>
      <br/>
      <table>
        <thead>
          <tr>
            <td><%= link_to "買い物を続ける",items_path,class: "btn btn-primary" %></td>
            <td><%= link_to "情報入力に進む",new_order_path(customers_path),class: "btn btn-success" %></td>
            <td>　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　</td>
            <td style="font-size : 20px;">合計金額　</td>
            <td style="font-size : 20px;"><%= @total.round.to_s(:delimited) %>　円</td>
          </tr>
        </thead>
      </table>
    <% else %>
      <div class="container contents text-center" style="height:300px">
        <%= image_tag '空カート.jpg', size:'220x220' %>
      </div>
      </br>

        <div class="container contents text-center" style="height:80px">
          <h4>カートに商品が入っていません</h4>
        </div>

      </br>
      <div class="container contents text-center style="height:80px"">
        <%= link_to "買い物を続ける",items_path,class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>