config/routes.rb
Rails.application.routes.draw do
  get 'genres/show'
  get 'customers/edit'
  get 'customers/show'
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords,], controllers: {
  registrations: "customer/registrations",
  sessions: 'customer/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

#Customer側のルーティング
  root 'homes#top'
  get 'about' => 'homes#about'
  resources :items, only: [:index, :show]

  delete 'cart_items/all_destroy' => 'cart_items#all_destroy'
  resources :cart_items, only: [:index, :create, :update, :destroy]

  resource :customers, only: [:show, :edit, :update]
  patch 'customers/withdraw' => 'customers#withdraw'
  get 'customers/unsubscribe' => 'customers#unsubscribe'

  post 'orders/confirm' => 'orders#confirm'
  get 'orders/thanx' => 'orders#thanx'
  resources :orders, only: [:index, :show, :new, :create]


  resources :addresses, except: [:new, :show]


  #admin側のルーティング
  namespace :admin do
    resources :items, except: [:destroy]
    resources :genres, except: [:new, :show, :destroy]
    resources :customers, except: [:new, :create, :destroy]
    resources :orders, only: [:index, :show, :update]
    get 'customer_orders/:id', to: 'orders#index_customer', as: 'customer_orders'
    patch 'orders_details/:id', to: 'order_details#update'
  end

end

app/models/address.rb
class Address < ApplicationRecord
  def full_address
    '〒' + postcode + ' ' + address + ' ' + name
  end
belongs_to :customer

validates :postcode, length: {is: 7},presence:true
validates :address,presence:true
validates :name,presence:true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord



  belongs_to :customer
  belongs_to :item


  def subtotal
    item.add_tax_sales_price * quantity
  end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :items, through: :cart_items
  has_many :order_items

  validates :last_name,presence:true
  validates :first_name,presence:true
  validates :last_name_kana,presence:true
  validates :first_name_kana,presence:true
  validates :postcode,presence:true,length: { is: 7 }
  validates :phone_num,presence:true
  validates :address,presence:true

  #devise情報をパスワードなしで更新できるメソッド
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  # enumの設定
  enum is_deleted: { withdraw: true, active: false}

  # フルネーム（nilの場合を除く）
  def full_name
    self.last_name + self.first_name
  end

  # フルネーム（姓名の間にスペースあり）（nilの場合を除く）
  def show_full_name
    self.last_name + " " + self.first_name
  end

  # フルネームカナ（nilの場合を除く）
  def full_name_kana
    self.last_name_kana + " " + self.last_name_kana
  end

  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
 has_many :item
end

app/models/item.rb
class Item < ApplicationRecord

 attachment :image
 belongs_to :genre

 has_many :cart_items, dependent: :destroy
 has_many :order_items, dependent: :destroy
 has_many :orders

 def add_tax_sales_price
  (self.price * 1.10).round
 end

end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :customer
  has_many :order_items, dependent: :destroy

  enum payment_method: { credit_card:0, transfer:1 }
  enum status: { wating_for_deposit:0, payment_confirmation:1, be_making:2, ready_to_ship:3, has_been_shiped:4}

  def billing_amount
    shipping_cost + total_payment
  end
  
  validates :postcode, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :payment_method, presence: true

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum making_status: { impossible:0, wating_for_making:1, be_making:2, has_been_shiped:3 }

  def add_tax_sales_price
    (self.price * 1.10).round
  end

  def subtotal
    self.add_tax_sales_price * quantity
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def show
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    @new_items = Item.order(created_at: :desc).limit(4)
  end

  def about
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.page(params[:page]).per(12)
    @item_count = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<header class="border-bottom sticky-top">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container-fluid">
      <div class="row">
        <%= link_to image_tag("ヘッダー画像.jpg"), root_path, id: "logo" %>
      </div>
      <!--deivseのフラッシュメッセージを表示 -->
        <p class="text-success"><%= notice %></p>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
              <p class="text-success">ようこそ、<%= current_customer.full_name %>さん！</p>
              <li class="nav-item mx-2 border d-brock p-3 rounded ">
                <%= link_to "マイページ", customers_path, class: "text-dark" %>
              </li>
              <li class="nav-item mx-2 border d-brock p-3 rounded">
                <%= link_to "商品一覧", items_path, class: "text-dark"%>
              </li>
              <li class="nav-it mx-2 border d-brock p-3 rounded">
                <%= link_to "カート", cart_items_path, class: "text-dark" %>
              </li>
              <li class="nav-item mx-2 border d-brock p-3 rounded">
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "text-dark" %>
              </li>
            <% elsif admin_signed_in? %>
              <li class="nav-item mx-2 border d-brock p-3 rounded">
                <%= link_to "商品一覧", admin_items_path, class: "text-dark" %>
              </li>
              <li class="nav-item mx-2 border d-brock p-3 rounded">
                <%= link_to "会員一覧", admin_customers_path, class: "text-dark" %>
              </li>
              <li class="nav-item mx-2 border d-brock p-3 rounded">
                <%= link_to "注文履歴一覧", admin_orders_path, class: "text-dark" %>
              </li>
              <li class="nav-item mx-2 border d-brock p-3 rounded">
                <%= link_to "ジャンル一覧", admin_genres_path, class: "text-dark" %>
              </li>
              <li class="nav-item mx-2 border d-brock p-3 rounded">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "text-dark" %>
              </li>
            <% else %>
              <li class="nav-item mx-2 border d-brock p-3 rounded">
                <%= link_to "About", about_path, class: "text-dark" %>
              </li>
              <li class="nav-item mx-2 border d-brock p-3 rounded">
                <%= link_to "商品一覧", items_path, class: "text-dark" %>
              </li>
              <li class="nav-item mx-2 border d-brock p-3 rounded">
                <%= link_to "新規登録", new_customer_registration_path, class: "text-dark" %>
              </li>
              <li class="nav-item mx-2 border d-brock p-3 rounded">
                <%= link_to "ログイン", new_customer_session_path, class: "text-dark" %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
        </div>
           <div class="input-group col-3 ml-auto mr-4 mb-1">
             <input type="text" class="form-control" placeholder="検索">
             <span class="input-group-btn">
               <button type="button" class="btn btn-primary">🔎</button>
             </span>
           </div>
        </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--header-->
    <%= render "layouts/header" %>
    <p class="text-alert"><%= alert %></p>

  <main>
    <%= yield %>
  </main>
    <!--footer-->
    <footer class="border-top container-fluid text-center p-1 mt-5 fixed-bottom">
          © HotSandMaker
    </footer>
  </div>
  </body>
</html>